site_name:        Julia Modeling and Inversion Toolbox
repo_url:         https://github.com/pawbz/JuMIT.jl
site_description: Seismic Waveform Modeling and Inversion
site_author:      Pawan Bharadwaj
theme: slate

extra_css:
          - assets/Documenter.css

extra_javascript:
          - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
              - assets/mathjaxhelper.js

markdown_extensions:
          - codehilite
          - extra
          - tables
          - fenced_code
          - mdx_math


extra_css:
          - assets/Documenter.css

docs_dir: 'src'

pages:
          - Home: index.md
          - Reference: reference.md
          - Tutorials: tut.md



